### PR TITLE
Create 2024_06_09_pyconcz23_wrapup_summary.md

### PR DESCRIPTION
**Pull request by baradrb**
First version

### CODE REVIEW

**Comment by hroncok** [comment]
The images seem missing.

**Comment by baradrb** [comment]
> The images seem missing.

I uploaded them to /images/... 🤷  Can you help?

**Comment by hroncok** [comment]
Not right now, perhaps tomorrow.

**Comment by hroncok** [comment]
Oh, the images are already in the master branch.

**Comment by frenzymadness** [comment]
The images uploaded to the master branch are *.jpg but the links in the text point to *.png so the images do not work even if I merge this PR to the master first.

**Comment by frenzymadness** [comment]
The text looks good to me :+1:

**Comment by baradrb** [comment]
Thanks! I didn't notice the wrong image format. I fixed it now. So please if it's good now let's merge it to the stars :)

**Comment by frenzymadness** [comment]
Last two errors:
* `/images/pyconcz23_juniors.jpg` is missing. I guess it should point to `pyconcz23_postits.jpg`
* `{static}/images/pyconcz23_pyramid.jpg` should be `{static}/images/pyconcz23_pyramid.JPG`

I'm gonna push a fixup commit to fix them both. It can be squashed during the merge.

**Comment by frenzymadness** [comment]
Hmm, I don't have rights to push here directly so here is the necessary change:

```diff
diff --git a/content/2024_06_09_pyconcz23_wrapup_summary.md b/content/2024_06_09_pyconcz23_wrapup_summary.md
index e5b9d63..f8f8ed7 100644
--- a/content/2024_06_09_pyconcz23_wrapup_summary.md
+++ b/content/2024_06_09_pyconcz23_wrapup_summary.md
@@ -66,7 +66,7 @@ Half (51.7%) attendees came from Prague, 31.3% came from the rest of the Czech R
 For most attendees (72.4%), this was their first PyCon CZ ever, while 10.6% have been to 3 or more Czech PyCons (remember that this was the 6th edition).
 Regarding attendees' self-perceived level of skill in Python programming, 15.9% called themselves expert Pythonistas, 43.9% stated they have done some advanced stuff in Python, 29.4% have done a few things here and there, and 10.8% were beginners in Python.
 
-![pieces of advice]({static}/images/pyconcz23_juniors.jpg)
+![pieces of advice]({static}/images/pyconcz23_postits.jpg)
 
 _Junior Guru post-its, photo by Honza Javorek_
 
@@ -212,7 +212,7 @@ _The final speech and giving thanks to the organisers and volunteers was an emot
 # 2024?
 What's next? Who knows! We have not formed a new organiser team, specifically, there is no main organiser ready to take on the challenge yet (as of June 2024). Should you wish to join our team, feel free to drop us a line at info@pycon.cz. And before we begin to prepare the next PyCon CZ, consider exploring and contributing to other community initiatives like PyLadies, Pyvo, PyData, and more!
 
-![human pyramid]({static}/images/pyconcz23_pyramid.jpg)
+![human pyramid]({static}/images/pyconcz23_pyramid.JPG)
 
 _Building a human pyramid is a tradition, photo by Honza Javorek_
 
```

**Comment by honzajavorek** [comment]
Is this ready for re-review?

**Review by clytaemnestra — APPROVED** [review]

**Comment by clytaemnestra** [comment]
Bulletpoints weren't rendered properly, so I fixed them. LGTM.

**Comment by clytaemnestra** [comment]
Waiting for @baradrb to confirm if this can already be merged or should we wait for more reviews.

**Pull request merged**
